require:
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - "**/Rakefile"
    - "**/Gemfile"
    - "*.gemspec"
    - "lib/**/*.rb"
    - "bin/**/*.rb"
    - "spec/**/*.rb"
    - "examples/**/*.rb"
    - ".simplecov"
  Exclude:
    - "Gemfile.lock"
    - "**/*.erb"
    - "gemfiles/**/*"
    - "bin/bench"

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 120

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/SuppressedException:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Metrics/AbcSize:
  Max: 38

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  Max: 13

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "**/spec/**/*.rb"
    - "**/*.rake"
    - "Rakefile"
    - "*.gemspec"

Metrics/PerceivedComplexity:
  Max: 8

Naming/AccessorMethodName:
  Enabled: true

Naming/ConstantName:
  Enabled: true

Naming/FileName:
  Enabled: true

Naming/MethodParameterName:
  AllowedNames:
    - ex

Naming/RescuedExceptionsVariableName:
  PreferredName: ex

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/DescribeClass:
  Enabled: true

RSpec/RepeatedDescription:
  Enabled: false

RSpec/ExampleLength:
  Enabled: true

RSpec/ExpectActual:
  Enabled: true

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/FilePath:
  Enabled: true

RSpec/InstanceVariable:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
  Enabled: true

RSpec/RepeatedExample:
  Enabled: true

Style/Documentation:
  Enabled: true
  Exclude:
    - "examples/**/*.rb"
    - "bin/**/*.rb"

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GlobalVars:
  Enabled: true

Style/ModuleFunction:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses_when_complex
  AllowSafeAssignment: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
