name: Lint
on:
  pull_request:
  push:
    only:
      - master
jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler: 2.2.14
          bundler-cache: true
      - run: bin/bundle check || bin/bundle --jobs=$(nproc) --retry=$(nproc)
      - run: bin/rubocop -P

  reek:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler: 2.2.14
          bundler-cache: true
      - run: bin/bundle check || bin/bundle --jobs=$(nproc) --retry=$(nproc)
      - run: bin/reek .
