name: ci
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler: 2.4.12
          bundler-cache: true
      - run: bin/bundle check || bin/bundle --jobs=$(nproc) --retry=$(nproc)
      - run: bin/rubocop -P

  reek:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler: 2.4.12
          bundler-cache: true
      - run: bin/bundle check || bin/bundle --jobs=$(nproc) --retry=$(nproc)
      - run: bin/reek .
