name: ci
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  coverage:
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler: 2.4.12
          bundler-cache: true

      - name: Install Code Climate reporter
        run: |
          sudo curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          sudo chmod +x ./cc-test-reporter
      - name: Generate Coverage
        env:
          CC_TEST_REPORTER_ID: e8ee6fccdc36b46acdc96337bb39b2c17ccd824e413649a4d94fd0dd35891d0f
        run: |
          export GIT_BRANCH=${GITHUB_REF#refs/heads/}
          export GIT_COMMIT_SHA=${GITHUB_SHA}
          echo $GIT_BRANCH
          echo $GIT_COMMIT_SHA
          ./cc-test-reporter before-build
          COV=true bin/rspec --require spec_helper
          ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?

  rspec:
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6, 2.7, '3.0', 3.1, 3.2]
        gemfile:
          - redis_3.x
          - redis_4.x
          - redis_5.x

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 2.4.12
          bundler-cache: true
      - run: bin/rspec --format doc
